# Generated by Django 6.1 on 2026-08-14 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReconcileRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('transaction_filename', models.CharField(max_length=255)),
                ('report_file', models.FileField(upload_to='reconcile_outputs/')),
                ('statements_uploaded', models.JSONField(blank=True, default=list)),
                ('statements_missing', models.JSONField(blank=True, default=list)),
                ('total_transactions', models.PositiveIntegerField(default=0)),
                ('sct_total', models.PositiveIntegerField(default=0)),
                ('sct_reconciled', models.PositiveIntegerField(default=0)),
                ('sct_flagged', models.PositiveIntegerField(default=0)),
                ('sct_no_statement', models.PositiveIntegerField(default=0)),
                ('nchl_total', models.PositiveIntegerField(default=0)),
                ('nchl_reconciled', models.PositiveIntegerField(default=0)),
                ('nchl_flagged', models.PositiveIntegerField(default=0)),
                ('khalti_total', models.PositiveIntegerField(default=0)),
                ('khalti_reconciled', models.PositiveIntegerField(default=0)),
                ('khalti_flagged', models.PositiveIntegerField(default=0)),
                ('failed_total', models.PositiveIntegerField(default=0)),
                ('failed_reconciled', models.PositiveIntegerField(default=0)),
                ('failed_pending', models.PositiveIntegerField(default=0)),
                ('failed_flagged', models.PositiveIntegerField(default=0)),
                ('manual_reversal_total', models.PositiveIntegerField(default=0)),
                ('manual_reversal_reconciled', models.PositiveIntegerField(default=0)),
                ('manual_reversal_pending', models.PositiveIntegerField(default=0)),
                ('manual_reversal_flagged', models.PositiveIntegerField(default=0)),
                ('system_reversal_total', models.PositiveIntegerField(default=0)),
                ('system_reversal_reconciled', models.PositiveIntegerField(default=0)),
                ('system_reversal_flagged', models.PositiveIntegerField(default=0)),
                ('need_reversal_count', models.PositiveIntegerField(default=0)),
                ('grand_total_reconciled', models.PositiveIntegerField(default=0)),
                ('grand_total_outstanding', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
