# Generated by Django 5.0.14 on 2026-08-18 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reconcile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reconcilerun',
            name='failed_offus_amount',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='reconcilerun',
            name='failed_offus_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='reconcilerun',
            name='failed_onus_amount',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='reconcilerun',
            name='failed_onus_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='reconcilerun',
            name='failed_reason_breakdown_offus',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='reconcilerun',
            name='failed_reason_breakdown_onus',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='reconcilerun',
            name='passed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reconcilerun',
            name='passed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reconcilerun',
            name='passed_by',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='reconcilerun',
            name='success_buckets_offus',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='reconcilerun',
            name='success_buckets_onus',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='reconcilerun',
            name='transaction_file',
            field=models.FileField(blank=True, null=True, upload_to='uploads/'),
        ),
        migrations.AddField(
            model_name='reconcilerun',
            name='uploaded_by',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
    ]
