# Generated by Django 5.0.14 on 2026-08-19 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reconcile', '0002_reconcilerun_failed_offus_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reconcilerun',
            name='bundle_zip',
            field=models.FileField(blank=True, null=True, upload_to='reconcile_bundles/'),
        ),
    ]
