# Generated by Django 5.0.14 on 2026-08-27 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reconcile', '0003_reconcilerun_bundle_zip'),
    ]

    operations = [
        migrations.AddField(
            model_name='reconcilerun',
            name='warnings',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
