# Generated by Django 5.0.14 on 2026-09-03 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reconcile', '0004_reconcilerun_warnings'),
    ]

    operations = [
        migrations.AddField(
            model_name='reconcilerun',
            name='issue_description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='reconcilerun',
            name='issue_notified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reconcilerun',
            name='issue_notified_by',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='reconcilerun',
            name='issue_notified_to',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='reconcilerun',
            name='issue_resolved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reconcilerun',
            name='issue_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reconcilerun',
            name='issue_updated_by',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
    ]
