# Generated by Django 5.0.14 on 2026-09-03 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reconcile', '0005_reconcilerun_issue_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reconcilerun',
            name='issue_notified_cc',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
