# Generated by Django 5.0.14 on 2026-07-20 07:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_amount_tracking'),
    ]

    operations = [
        migrations.AddField(
            model_name='processinglog',
            name='already_reversed_amount',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='processinglog',
            name='already_reversed_charge',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='processinglog',
            name='already_reversed_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='processinglog',
            name='bank_statement_checked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='processinglog',
            name='bank_statement_checked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='processinglog',
            name='bank_statement_checked_by',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='processinglog',
            name='bank_statement_filename',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='processinglog',
            name='duplicate_source_skipped',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='processinglog',
            name='failed_credited_amount',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='processinglog',
            name='failed_credited_charge',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='processinglog',
            name='failed_credited_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='processinglog',
            name='failed_kept_amount',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='processinglog',
            name='failed_kept_charge',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='processinglog',
            name='processing_duration_ms',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='SeenNetworkReferenceId',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref_id', models.CharField(db_index=True, max_length=64, unique=True)),
                ('first_seen_at', models.DateTimeField(auto_now_add=True)),
                ('source_log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seen_refs', to='core.processinglog')),
            ],
        ),
    ]
