# Generated by Django 5.0.14 on 2026-07-21 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_processinglog_already_reversed_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='processinglog',
            name='data_through_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
