# Generated by Django 5.0.14 on 2026-07-22 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_processinglog_data_through_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='processinglog',
            name='failed_offus_amount',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='processinglog',
            name='failed_offus_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='processinglog',
            name='failed_onus_amount',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='processinglog',
            name='failed_onus_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='processinglog',
            name='failed_reason_breakdown_offus',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='processinglog',
            name='failed_reason_breakdown_onus',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
