# Generated by Django 5.0.14 on 2026-07-28 09:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_processinglog_failed_offus_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='processinglog',
            name='bank_statement_type',
            field=models.CharField(blank=True, choices=[('global', 'Global IME Bank'), ('prabhu', 'Prabhu Bank')], default='', max_length=10),
        ),
        migrations.AddField(
            model_name='processinglog',
            name='prabhu_reversal_amount',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='processinglog',
            name='prabhu_reversal_count',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='MemberAggregatorStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_name', models.CharField(blank=True, default='', max_length=255)),
                ('aggregator', models.CharField(blank=True, default='', max_length=255)),
                ('success_count', models.IntegerField(default=0)),
                ('success_amount', models.FloatField(default=0.0)),
                ('failed_count', models.IntegerField(default=0)),
                ('failed_amount', models.FloatField(default=0.0)),
                ('reversal_count', models.IntegerField(default=0)),
                ('reversal_amount', models.FloatField(default=0.0)),
                ('log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member_aggregator_stats', to='core.processinglog')),
            ],
            options={
                'indexes': [models.Index(fields=['member_name', 'aggregator'], name='core_member_member__1fbd23_idx')],
            },
        ),
    ]
