# Generated by Django 5.0.14 on 2026-07-29 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_processinglog_bank_statement_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='processinglog',
            name='already_reversed_nchl_amount',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='processinglog',
            name='already_reversed_nchl_count',
            field=models.IntegerField(default=0),
        ),
    ]
