# Generated by Django 5.0.14 on 2026-07-29 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_processinglog_already_reversed_nchl_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processinglog',
            name='bank_statement_type',
            field=models.CharField(blank=True, choices=[('global', 'Global IME Bank'), ('prabhu', 'Prabhu Bank'), ('both', 'Global IME Bank + Prabhu Bank')], default='', max_length=10),
        ),
    ]
