# Generated by Django 5.0.14 on 2026-07-29 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_processinglog_bank_statement_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='processinglog',
            name='onus_already_success_amount',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='processinglog',
            name='onus_already_success_charge',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='processinglog',
            name='onus_already_success_count',
            field=models.IntegerField(default=0),
        ),
    ]
