# Generated by Django 5.0.14 on 2026-07-31 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_processinglog_onus_already_success_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='processinglog',
            name='already_reversed_onus_success_amount',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='processinglog',
            name='already_reversed_onus_success_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='processinglog',
            name='reversal_system_onus_amount',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='processinglog',
            name='reversal_system_onus_charge',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='processinglog',
            name='reversal_system_onus_count',
            field=models.IntegerField(default=0),
        ),
    ]
