# Generated by Django 5.0.14 on 2026-07-31 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_processinglog_already_reversed_onus_success_amount_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(help_text="Display name, e.g. 'Global IME Bank'.", max_length=100)),
                ('keyword', models.CharField(help_text="Upper-cased, case-insensitive substring matched against the 'Debtor Bank' (and 'Creditor Bank') column, e.g. 'GLOBAL' matches 'Global IME Bank'. Keep this short and specific.", max_length=50, unique=True)),
                ('debit_account_number', models.CharField(help_text="Placed in 'Debit Account Number' for any reversal row whose Debtor Bank matches this Keyword.", max_length=50)),
                ('is_own_bank', models.BooleanField(default=False, help_text='Check for Global IME Bank / Prabhu Bank and any other bank we operate — this bank then counts toward On-Us determination (Debtor Bank and Creditor Bank both being one of our own banks), which drives the On-Us "already successful" checks.')),
                ('is_active', models.BooleanField(default=True, help_text='Untick to stop matching this bank without deleting the row.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['bank_name'],
            },
        ),
        migrations.AddField(
            model_name='processinglog',
            name='onus_system_reversal_flagged_amount',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='processinglog',
            name='onus_system_reversal_flagged_count',
            field=models.IntegerField(default=0),
        ),
    ]
