# Generated by Django 5.0.14 on 2026-08-26 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_processinglog_already_reversed_khalti_amount_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VerificationBankContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(help_text="Display name, e.g. 'Agriculture Development Bank Ltd (ADBL)'.", max_length=100)),
                ('keyword', models.CharField(help_text="Upper-cased, case-insensitive substring matched against the 'Creditor Bank' column, e.g. 'GARIMA' matches 'Garima Bikas Bank Ltd'. Keep this short and specific.", max_length=50, unique=True)),
                ('to_emails', models.CharField(help_text="Comma-separated 'To' address(es) for this bank's verification requests.", max_length=500)),
                ('cc_emails', models.CharField(blank=True, default='', help_text="Optional comma-separated 'Cc' address(es).", max_length=500)),
                ('is_active', models.BooleanField(default=True, help_text='Untick to stop matching this bank without deleting the row.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['bank_name'],
            },
        ),
    ]
