# Generated by Django 5.0.14 on 2026-08-26 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_verificationbankcontact'),
    ]

    operations = [
        migrations.CreateModel(
            name='MailSignature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', help_text='Leave blank for a generic/shared mailbox — the signature will show only the title below.', max_length=150)),
                ('title', models.CharField(default='Tech Operation Department', help_text="Shown under the name (or alone, if Name is blank), e.g. 'Tech Operation Department'.", max_length=150)),
                ('mobile', models.CharField(blank=True, default='', help_text="Optional — leave blank to omit the 'Mobile:' line entirely.", max_length=30)),
                ('is_active', models.BooleanField(default=True, help_text='The most recently updated active row is used to sign outgoing verification emails.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
    ]
