# Generated by Django 5.0.14 on 2026-08-26 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_mailsignature'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailsignature',
            name='address',
            field=models.CharField(blank=True, default='', help_text='Optional — leave blank to use the MAIL_SIGNATURE_ADDRESS default.', max_length=255),
        ),
        migrations.AddField(
            model_name='mailsignature',
            name='company',
            field=models.CharField(blank=True, default='', help_text='Optional — leave blank to use the MAIL_SIGNATURE_COMPANY default.', max_length=150),
        ),
        migrations.AddField(
            model_name='mailsignature',
            name='toll_free',
            field=models.CharField(blank=True, default='', help_text='Optional — leave blank to use the MAIL_SIGNATURE_TOLL_FREE default.', max_length=50),
        ),
        migrations.AddField(
            model_name='mailsignature',
            name='website',
            field=models.CharField(blank=True, default='', help_text='Optional — leave blank to use the MAIL_SIGNATURE_WEBSITE default.', max_length=100),
        ),
    ]
