# Generated by Django 5.0.14 on 2026-09-03 11:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_mailsignature_address_mailsignature_company_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='mailsignature',
            name='user',
            field=models.ForeignKey(blank=True, help_text='Whose signatures these are — blank only for legacy rows created before per-user signatures.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mail_signatures', to=settings.AUTH_USER_MODEL),
        ),
    ]
