# Generated by Django 5.0.14 on 2026-09-04 05:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_mailsignature_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can_reversal', models.BooleanField(default=False, help_text='Generate reversal files.')),
                ('can_reconcile', models.BooleanField(default=False, help_text='Run reconciliations.')),
                ('can_verification_format', models.BooleanField(default=False, help_text='Use the Verification format tool.')),
                ('can_check_statements', models.BooleanField(default=False, help_text='Check a generated file against a bank statement.')),
                ('can_audit_log', models.BooleanField(default=False, help_text='View the audit log.')),
                ('can_bank_contacts', models.BooleanField(default=False, help_text='Add/update verification bank contacts.')),
                ('can_issuer_bank_accounts', models.BooleanField(default=False, help_text='Add issuer bank accounts.')),
                ('can_make_users', models.BooleanField(default=False, help_text='Create/update/delete user logins.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='access', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
