# Generated by Django 5.0.14 on 2026-09-04 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_useraccess_backfill'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduledReportRecipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(choices=[('dispute_alert', 'Dispute/timeout alert (every minute)'), ('daily_report', 'Daily transaction report (09:00)')], max_length=20)),
                ('label', models.CharField(blank=True, default='', help_text="Optional — e.g. 'Ops team', just for your own reference.", max_length=100)),
                ('to_emails', models.CharField(help_text='Comma-separated.', max_length=500)),
                ('cc_emails', models.CharField(blank=True, default='', help_text='Comma-separated, optional.', max_length=500)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['report_type', 'label'],
            },
        ),
        migrations.CreateModel(
            name='SchedulerJobState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_key', models.CharField(choices=[('dispute_alert', 'Dispute/timeout alert (every minute)'), ('daily_report', 'Daily transaction report (09:00)')], max_length=20, unique=True)),
                ('is_enabled', models.BooleanField(default=False)),
                ('last_checked_at', models.DateTimeField(blank=True, help_text="Dispute alert only — rolling window cursor for what's already been checked.", null=True)),
                ('last_run_at', models.DateTimeField(blank=True, null=True)),
                ('last_result', models.CharField(blank=True, default='', max_length=255)),
                ('updated_by', models.CharField(blank=True, default='', max_length=150)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='useraccess',
            name='can_scheduler',
            field=models.BooleanField(default=False, help_text='Manage the dispute/timeout alert and daily report scheduler.'),
        ),
    ]
