# Generated by Django 5.0.14 on 2026-09-04 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_scheduler'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertedTimeoutTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('network_reference_id', models.CharField(max_length=20, unique=True)),
                ('alerted_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-alerted_at'],
            },
        ),
    ]
