# Generated by Django 5.0.14 on 2026-09-08 05:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_disputenotificationevent_usernotificationpreference'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MailServerConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(blank=True, default='', help_text="Optional — a name to tell rows apart, e.g. 'Finance dept SMTP'.", max_length=100)),
                ('host', models.CharField(blank=True, default='', help_text='e.g. smtp.office365.com — leave blank to use the SMTP_HOST default.', max_length=255)),
                ('port', models.PositiveIntegerField(default=587)),
                ('username', models.CharField(blank=True, default='', help_text='Usually the full mailbox email address — leave blank to use the SMTP_USERNAME default.', max_length=255)),
                ('password', models.CharField(blank=True, default='', help_text='Leave blank when editing to keep the current password.', max_length=255)),
                ('from_email', models.CharField(blank=True, default='', help_text='Optional — leave blank to send as Username (or the SMTP_FROM_EMAIL default).', max_length=255)),
                ('encryption', models.CharField(choices=[('tls', 'TLS'), ('ssl', 'SSL'), ('none', 'None')], default='tls', max_length=10)),
                ('is_active', models.BooleanField(default=True, help_text="The most recently updated active row is used to send this user's outgoing mail.")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, help_text='Whose SMTP account this is — blank only for a shared/system fallback row.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mail_server_configs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
    ]
