# Generated by Django 5.0.14 on 2026-09-08 05:20

import core.crypto
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_mailserverconfig'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailserverconfig',
            name='password',
            field=core.crypto.EncryptedCharField(blank=True, default='', help_text='Leave blank when editing to keep the current password. Stored encrypted, never in plaintext.', max_length=512),
        ),
    ]
